// Sistema de traducciones ES/EN para el CRM Fix A Trip
// Uso: t('clave', lang)  — lang es 'es' o 'en'

export function t(key, lang = 'en') {
  const d = strings[lang] || strings.en;
  return d[key] ?? strings.es[key] ?? key;
}

const strings = {
  // ─────────────────── ESPAÑOL ───────────────────
  es: {
    // ── Navegación ──────────────────────────────
    'nav.home':          'Inicio',
    'nav.leads':         'Leads',
    'nav.chats':         'Chats',
    'nav.contacts':      'Contactos',
    'nav.email':         'Correo',
    'nav.calls':         'Llamadas',
    'nav.alerts':        'Alertas',
    'nav.menus':         'Menús',
    'nav.more':          'Más',
    'nav.light':         'Claro',
    'nav.dark':          'Oscuro',
    'nav.logout':        'Salir',
    'nav.invoices':      'Facturas',
    'nav.contracts':     'Contratos',
    'nav.libgigi':       'Biblioteca GIGI',
    'nav.team':          'Equipo',
    'nav.booking':       'Booking',
    'nav.proposal':      'Propuesta IA',
    'nav.itinerary':     'Itinerarios',
    'nav.suppliers':     'Proveedores',
    'nav.metrics':       'Métricas',
    'nav.financial':     'Financiero',
    'nav.goals':         'Metas',
    'nav.apidocs':       'API Docs',
    'nav.tools':         'Herramientas',
    'nav.integrations':  'Integraciones',
    'nav.settings':      'Ajustes',
    'nav.users':         'Usuarios',
    'nav.calendar':      'Calendario',
    'nav.search':        'Buscar...',
    'sec.finance':       'Finanzas',
    'sec.gigi':          'GIGI',
    'sec.comms':         'Comunicación',
    'sec.trips':         'Viajes',
    'sec.reports':       'Reportes',
    'sec.config':        'Config',

    // ── Tiempo relativo ──────────────────────────
    'time.now':          'ahora',
    'time.min':          'hace {n}m',
    'time.hours':        'hace {n}h',
    'time.days':         'hace {n}d',
    'time.yesterday':    'ayer',
    'time.just':         'ahora',

    // ── Común ────────────────────────────────────
    'common.loading':    'Cargando...',
    'common.save':       'Guardar',
    'common.saving':     'Guardando...',
    'common.cancel':     'Cancelar',
    'common.delete':     'Eliminar',
    'common.edit':       'Editar',
    'common.close':      'Cerrar',
    'common.confirm':    'Confirmar',
    'common.yes':        'Sí',
    'common.no':         'No',
    'common.search':     'Buscar...',
    'common.noResults':  'Sin resultados',
    'common.viewMore':   'Ver →',
    'common.all':        'Todos',
    'common.total':      'Total',
    'common.created':    'Creado',
    'common.error':      'Error',
    'common.success':    'Listo',
    'common.send':       'Enviar',
    'common.sending':    'Enviando...',
    'common.add':        'Agregar',
    'common.adding':     'Agregando...',
    'common.update':     'Actualizar',
    'common.create':     'Crear',
    'common.back':       'Atrás',
    'common.next':       'Siguiente',
    'common.preview':    'Vista previa',
    'common.download':   'Descargar',
    'common.copy':       'Copiar',
    'common.copied':     '¡Copiado!',
    'common.unknown':    'Desconocido',
    'common.noName':          'Sin nombre',
    'common.enableNotifs':    'Activa las notificaciones',
    'common.enableNotifsDesc':'Para recibir avisos cuando alguien escriba, agrega esta app a tu pantalla de inicio. Toca ⎋ y luego "Agregar a inicio"',

    // ── Dashboard ────────────────────────────────
    'dash.greet.morning':  'Buenos días',
    'dash.greet.afternoon':'Buenas tardes',
    'dash.greet.evening':  'Buenas noches',
    'dash.stat.activeLeads':'Leads activos',
    'dash.stat.noResponse': 'Sin respuesta',
    'dash.stat.alerts':     'Alertas',
    'dash.stat.revenue':    'Ingresos mes',
    'dash.section.leads':   'Leads recientes',
    'dash.section.alerts':  'Alertas',
    'dash.section.calls':   'Llamadas',
    'dash.section.emails':  'Correos',
    'dash.empty.leads':     'Sin leads',
    'dash.empty.alerts':    'Sin alertas',
    'dash.empty.calls':     'Sin llamadas',
    'dash.empty.emails':    'Sin correos',
    'dash.metrics':         'Ver métricas completas →',
    'dash.noSubject':       '(Sin asunto)',
    'dash.outbound':        'Saliente',
    'dash.inbound':         'Entrante',

    // ── Alertas ──────────────────────────────────
    'alerts.title':          'Alertas',
    'alerts.markAllSeen':    'Marcar todas como vistas',
    'alerts.markSeen':       'Marcar vista',
    'alerts.hide':           'Ocultar alerta',
    'alerts.empty':          'Sin alertas',
    'alerts.tab.unseen':     'Sin ver',
    'alerts.tab.all':        'Todas',
    'alerts.tab.seen':       'Vistas',
    'alerts.filter.all':     'Todos',
    'alerts.status.pending':    'Pendiente',
    'alerts.status.en_proceso': 'En proceso',
    'alerts.status.cotizado':   'Cotizado',
    'alerts.status.confirmado': 'Confirmado',
    'alerts.status.pagado':     'Pagado',
    'alerts.type.intencion_compra': 'Intención de compra',
    'alerts.type.grupo_grande':     'Grupo grande',
    'alerts.type.web_form':         'Formulario web',
    'alerts.type.email':            'Email',
    'alerts.type.default':          'Alerta',

    // ── Email ─────────────────────────────────────
    'email.title':        'Email',
    'email.inbox':        'Bandeja Fix A Trip',
    'email.sync':         'Sincronizar',
    'email.compose':      'Redactar',
    'email.tab.received': 'Recibidos',
    'email.tab.sent':     'Enviados',
    'email.tab.all':      'Todos',
    'email.new':          'Nuevo correo',
    'email.sendFrom':     'Enviar desde',
    'email.to':           'Para',
    'email.subject':      'Asunto',
    'email.message':      'Mensaje',
    'email.fillAll':      'Completa todos los campos',
    'email.send':         '✉ Enviar',
    'email.sending':      'Enviando...',
    'email.cancel':       'Cancelar',
    'email.empty.received': 'Sin correos recibidos',
    'email.empty.sent':   'Sin correos enviados',
    'email.empty.all':    'Sin correos',
    'email.hint.received': 'Los correos de la bandeja de entrada aparecerán aquí.',
    'email.hint.sent':    'Los correos enviados desde el CRM aparecerán aquí.',
    'email.cta':          '✉ Redactar correo',
    'email.select':       'Selecciona un correo',
    'email.delete':       'Eliminar',
    'email.reply':        '↩ Responder',
    'email.noContent':    '(Sin contenido)',
    'email.syncing':      'Sincronizando bandeja...',
    'email.to_label':     'Para:',
    'email.from_label':   'De:',
    'email.account_label':'Cuenta:',
    'email.noSubject':    'Sin asunto',
    'email.confirmDelete':'¿Eliminar este correo?',

    // ── Llamadas ─────────────────────────────────
    'calls.title':        'Llamadas',
    'calls.tab.logs':     '📞 Llamadas',
    'calls.tab.twilio':   '🎙 Grabaciones Twilio',
    'calls.stat.total':   'Total',
    'calls.stat.completed':'Completadas',
    'calls.stat.noAnswer': 'Sin respuesta',
    'calls.stat.recordings':'Grabaciones',
    'calls.stat.duration': 'Tiempo total',
    'calls.filter.number': 'Buscar número o agente...',
    'calls.filter.allStatus': 'Todos los estados',
    'calls.filter.allRec':    'Todas las grabaciones',
    'calls.filter.withRec':   'Con grabación',
    'calls.filter.noRec':     'Sin grabación',
    'calls.col.number':   'Número',
    'calls.col.agent':    'Agente',
    'calls.col.status':   'Estado',
    'calls.col.duration': 'Duración',
    'calls.col.date':     'Fecha',
    'calls.col.lead':     'Lead',
    'calls.col.recording':'Grabación',
    'calls.empty':        'Sin llamadas registradas',
    'calls.status.completed':    'Completada',
    'calls.status.no-answer':    'Sin respuesta',
    'calls.status.busy':         'Ocupado',
    'calls.status.failed':       'Fallida',
    'calls.status.initiated':    'Iniciada',
    'calls.status.ringing':      'Timbrando',
    'calls.status.in-progress':  'En curso',
    'calls.status.canceled':     'Cancelada',
    'calls.outbound':            'Saliente',
    'calls.inbound':             'Entrante',
    'calls.rec.loading':         'Cargando grabación...',
    'calls.rec.error':           'Error cargando grabación',
    'calls.rec.confirmDelete':   '¿Eliminar grabación?',
    'calls.rec.deleting':        'Eliminando...',
    'calls.rec.noAudio':         'Tu navegador no soporta audio HTML5.',
    'calls.rec.play':            '▶ Reproducir',
    'calls.rec.pause':           '⏸ Pausar',
    'calls.rec.transcribe':      '✍ Transcribir',
    'calls.rec.processing':      'Procesando...',
    'calls.rec.download':        '⬇ Descargar',
    'calls.rec.delete':          'Eliminar grabación',
    'calls.rec.conversation':    'Conversación ({n} turnos)',
    'calls.rec.transcript':      'Transcripción',
    'calls.rec.noTranscript':    'Sin contenido transcribible en esta grabación.',
    'calls.rec.agent':           'Agente',
    'calls.rec.client':          'Cliente',
    'calls.rec.stereo':          'Estéreo',
    'calls.rec.mono':            'Mono',
    'calls.rec.voicemail':       '📩 Voicemail',
    'calls.rec.call':            '📞 Llamada',
    'calls.rec.play_btn':        'Reproducir grabación',
    'calls.rec.close_btn':       'Cerrar player',

    // ── Leads ──────────────────────────────────────
    'leads.tab.chat':      'Chat',
    'leads.tab.notes':     'Notas',
    'leads.tab.tasks':     'Tareas',
    'leads.tab.calls':     'Llamadas',
    'leads.tab.activity':  'Actividad',
    'leads.tab.tags':      'Tags',
    'leads.tab.extra':     'Extra',
    'leads.tab.trip':      'Viaje',
    'leads.tab.contacts':  'Contactos',
    'leads.tab.intNotes':  'Notas int.',
    'leads.tab.ai':        'IA',
    'leads.stage':         'Etapa...',
    'leads.select':        'Seleccionar',
    'leads.automate':      'Automatiza',
    'leads.newLead':       'Nuevo lead',
    'leads.dormant':       'Dormidos',
    'leads.dormantTitle':  'Leads sin actividad en más de 7 días',
    'leads.botOn':         'ACTIVO',
    'leads.botOff':        'APAGADO',
    'leads.summarize':     'Resumir con IA',
    'leads.summarizing':   'Resumiendo...',
    'leads.merge':         'Unir leads',
    'leads.mergeTitle':    'Unir con otro lead',
    'leads.mergeDesc':     'El lead {title} se mantendrá. Los mensajes, notas, tareas y contactos del otro lead se transferirán aquí y ese lead será eliminado.',
    'leads.mergeSearch':   'Buscar lead por nombre o contacto...',
    'leads.outbound':      'Saliente',
    'leads.inbound':       'Entrante',
    'leads.noSubject':     'Sin asunto',
    'leads.status.completed':  'Completada',
    'leads.status.no-answer':  'Sin respuesta',
    'leads.status.busy':       'Ocupado',
    'leads.status.failed':     'Fallida',
    'leads.status.initiated':  'Iniciada',
    'leads.status.ringing':    'Timbrando',
    'leads.status.in-progress':'En curso',
    'leads.status.canceled':   'Cancelada',
    'leads.rec.loading':       'Cargando grabaciones...',
    'leads.rec.noTwilio':      'Sin grabaciones en Twilio',
    'leads.rec.errorDelete':   'Error al eliminar: ',

    // ── Contactos ──────────────────────────────────
    'contacts.editTitle':    'Editar contacto',
    'contacts.newTitle':     'Nuevo contacto',
    'contacts.name':         'Nombre *',
    'contacts.phone':        'Teléfono',
    'contacts.email':        'Email',
    'contacts.company':      'Empresa',
    'contacts.notes':        'Notas',
    'contacts.namePH':       'Juan Pérez',
    'contacts.phonePH':      '+1234567890',
    'contacts.emailPH':      'correo@ejemplo.com',
    'contacts.companyPH':    'Nombre empresa',
    'contacts.notesPH':      'Notas internas...',
    'contacts.dupWarning':   'Ya existe: {name}. ¿Crear de todas formas?',
    'contacts.viewExisting': 'Ver contacto existente',
    'contacts.createAnyway': 'Crear de todas formas',
    'contacts.import':       'Importar contactos desde CSV',
    'contacts.importStep':   'Paso {n} de 2',
    'contacts.importHint':   'La primera fila debe ser el encabezado. Luego podrás mapear las columnas.',
    'contacts.importClick':  'Click para seleccionar CSV',
    'contacts.importMap':    'Asigna cada columna del CSV al campo correspondiente.',
    'contacts.importPreview':'Ver vista previa →',
    'contacts.importBack':   'Atrás',
    'contacts.importRequire':'Debes mapear al menos la columna "Nombre".',
    'contacts.importPreviewLabel': 'Vista previa ({n} de {total} filas):',
    'contacts.importBtn':    'Importar {n} contactos',
    'contacts.importDone':   'Importación completada',
    'contacts.importResult': '{n} contactos creados · {s} omitidos (duplicados)',
    'contacts.dupDetect':    'Detectar duplicados',
    'contacts.dupDesc':      'Contactos con el mismo teléfono o nombre idéntico',
    'contacts.dupSearching': 'Buscando duplicados...',
    'contacts.dupNone':      'No se encontraron contactos duplicados',
    'contacts.dupPhone':     '📞 Mismo teléfono',
    'contacts.dupName':      '👤 Mismo nombre',
    'contacts.dupKeep':      'Mantener "{name}"',
    'contacts.dupMerging':   'Combinando...',
    'contacts.dupSkip':      'Omitir',
    'contacts.col.name':     'Nombre',
    'contacts.col.phone':    'Teléfono',
    'contacts.col.email':    'Email',
    'contacts.col.company':  'Empresa',
    'contacts.exportCsv':    'Exportar CSV',
    'contacts.export':       'Exportar',
    'contacts.import2':      'Importar',
    'contacts.newShort':     'Nuevo',

    // ── Inbox ──────────────────────────────────────
    'inbox.title':           'ENTRADAS',
    'inbox.empty':           'Sin conversaciones',
    'inbox.search':          'Buscar...',
    'inbox.send':            'Enviar',
    'inbox.typePlaceholder': 'Escribe un mensaje...',
    'inbox.noMessages':      'Sin mensajes',
    'inbox.inbound':         'Entrantes',
    'inbox.outbound':        'Salientes',
    'inbox.channel.whatsapp':'WhatsApp',
    'inbox.channel.sms':     'SMS',
    'inbox.channel.email':   'Email',

    // ── Settings ───────────────────────────────────
    'settings.templates':      'Plantillas de respuesta rápida',
    'settings.templatesDesc':  'Respuestas predefinidas para usar en el inbox.',
    'settings.templatesVars':  'Variables: {{nombre}}, {{telefono}}, {{fecha}}, {{fecha_checkin}}, {{monto}}, {{agente}}',
    'settings.general':        'General',
    'settings.editTemplate':   'Editando plantilla',
    'settings.newTemplate':    'Nueva plantilla',
    'settings.titlePH':        'Título (ej: Bienvenida)',
    'settings.categoryPH':     'Categoría (ej: Ventas)',
    'settings.textPH':         'Texto... puedes usar las variables de arriba',
    'settings.noTemplates':    'Sin plantillas aún',
    'settings.customFields':   'Campos personalizados',
    'settings.customFieldsDesc':'Agrega campos extra a leads y contactos',
    'settings.cfLeads':        'Leads',
    'settings.cfContacts':     'Contactos',
    'settings.cfEmpty':        'Sin campos personalizados aún',
    'settings.cfNew':          'Nuevo campo',
    'settings.cfLabelPH':      'Etiqueta del campo (ej: Presupuesto, Cargo)',
    'settings.cfText':         'Texto',
    'settings.cfNumber':       'Número',
    'settings.cfDate':         'Fecha',
    'settings.cfSelect':       'Selección',
    'settings.cfOptionsPH':    'Opciones separadas por coma (ej: Opción 1, Opción 2)',
    'settings.cfAdd':          'Agregar campo',
  },

  // ─────────────────── ENGLISH ───────────────────
  en: {
    // ── Navigation ──────────────────────────────
    'nav.home':          'Home',
    'nav.leads':         'Leads',
    'nav.chats':         'Chats',
    'nav.contacts':      'Contacts',
    'nav.email':         'Email',
    'nav.calls':         'Calls',
    'nav.alerts':        'Alerts',
    'nav.menus':         'Menus',
    'nav.more':          'More',
    'nav.light':         'Light',
    'nav.dark':          'Dark',
    'nav.logout':        'Logout',
    'nav.invoices':      'Invoices',
    'nav.contracts':     'Contracts',
    'nav.libgigi':       'GIGI Library',
    'nav.team':          'Team',
    'nav.booking':       'Booking',
    'nav.proposal':      'AI Proposal',
    'nav.itinerary':     'Itineraries',
    'nav.suppliers':     'Suppliers',
    'nav.metrics':       'Metrics',
    'nav.financial':     'Financial',
    'nav.goals':         'Goals',
    'nav.apidocs':       'API Docs',
    'nav.tools':         'Tools',
    'nav.integrations':  'Integrations',
    'nav.settings':      'Settings',
    'nav.users':         'Users',
    'nav.calendar':      'Calendar',
    'nav.search':        'Search...',
    'sec.finance':       'Finance',
    'sec.gigi':          'GIGI',
    'sec.comms':         'Communication',
    'sec.trips':         'Trips',
    'sec.reports':       'Reports',
    'sec.config':        'Config',

    // ── Time ────────────────────────────────────
    'time.now':          'just now',
    'time.min':          '{n}m ago',
    'time.hours':        '{n}h ago',
    'time.days':         '{n}d ago',
    'time.yesterday':    'yesterday',
    'time.just':         'just now',

    // ── Common ───────────────────────────────────
    'common.loading':    'Loading...',
    'common.save':       'Save',
    'common.saving':     'Saving...',
    'common.cancel':     'Cancel',
    'common.delete':     'Delete',
    'common.edit':       'Edit',
    'common.close':      'Close',
    'common.confirm':    'Confirm',
    'common.yes':        'Yes',
    'common.no':         'No',
    'common.search':     'Search...',
    'common.noResults':  'No results',
    'common.viewMore':   'View →',
    'common.all':        'All',
    'common.total':      'Total',
    'common.created':    'Created',
    'common.error':      'Error',
    'common.success':    'Done',
    'common.send':       'Send',
    'common.sending':    'Sending...',
    'common.add':        'Add',
    'common.adding':     'Adding...',
    'common.update':     'Update',
    'common.create':     'Create',
    'common.back':       'Back',
    'common.next':       'Next',
    'common.preview':    'Preview',
    'common.download':   'Download',
    'common.copy':       'Copy',
    'common.copied':     'Copied!',
    'common.unknown':    'Unknown',
    'common.noName':          'No name',
    'common.enableNotifs':    'Enable notifications',
    'common.enableNotifsDesc':'To receive alerts when someone messages, add this app to your home screen. Tap ⎋ then "Add to Home Screen"',

    // ── Dashboard ────────────────────────────────
    'dash.greet.morning':  'Good morning',
    'dash.greet.afternoon':'Good afternoon',
    'dash.greet.evening':  'Good evening',
    'dash.stat.activeLeads':'Active leads',
    'dash.stat.noResponse': 'No response',
    'dash.stat.alerts':     'Alerts',
    'dash.stat.revenue':    'Monthly revenue',
    'dash.section.leads':   'Recent leads',
    'dash.section.alerts':  'Alerts',
    'dash.section.calls':   'Calls',
    'dash.section.emails':  'Emails',
    'dash.empty.leads':     'No leads',
    'dash.empty.alerts':    'No alerts',
    'dash.empty.calls':     'No calls',
    'dash.empty.emails':    'No emails',
    'dash.metrics':         'View full metrics →',
    'dash.noSubject':       '(No subject)',
    'dash.outbound':        'Outbound',
    'dash.inbound':         'Inbound',

    // ── Alerts ───────────────────────────────────
    'alerts.title':          'Alerts',
    'alerts.markAllSeen':    'Mark all as seen',
    'alerts.markSeen':       'Mark seen',
    'alerts.hide':           'Hide alert',
    'alerts.empty':          'No alerts',
    'alerts.tab.unseen':     'Unseen',
    'alerts.tab.all':        'All',
    'alerts.tab.seen':       'Seen',
    'alerts.filter.all':     'All',
    'alerts.status.pending':    'Pending',
    'alerts.status.en_proceso': 'In progress',
    'alerts.status.cotizado':   'Quoted',
    'alerts.status.confirmado': 'Confirmed',
    'alerts.status.pagado':     'Paid',
    'alerts.type.intencion_compra': 'Purchase intent',
    'alerts.type.grupo_grande':     'Large group',
    'alerts.type.web_form':         'Web form',
    'alerts.type.email':            'Email',
    'alerts.type.default':          'Alert',

    // ── Email ─────────────────────────────────────
    'email.title':        'Email',
    'email.inbox':        'Fix A Trip Inbox',
    'email.sync':         'Sync',
    'email.compose':      'Compose',
    'email.tab.received': 'Inbox',
    'email.tab.sent':     'Sent',
    'email.tab.all':      'All',
    'email.new':          'New email',
    'email.sendFrom':     'Send from',
    'email.to':           'To',
    'email.subject':      'Subject',
    'email.message':      'Message',
    'email.fillAll':      'Please fill in all fields',
    'email.send':         '✉ Send',
    'email.sending':      'Sending...',
    'email.cancel':       'Cancel',
    'email.empty.received': 'No received emails',
    'email.empty.sent':   'No sent emails',
    'email.empty.all':    'No emails',
    'email.hint.received': 'Inbox emails will appear here.',
    'email.hint.sent':    'Emails sent from the CRM will appear here.',
    'email.cta':          '✉ Compose email',
    'email.select':       'Select an email',
    'email.delete':       'Delete',
    'email.reply':        '↩ Reply',
    'email.noContent':    '(No content)',
    'email.syncing':      'Syncing inbox...',
    'email.to_label':     'To:',
    'email.from_label':   'From:',
    'email.account_label':'Account:',
    'email.noSubject':    'No subject',
    'email.confirmDelete':'Delete this email?',

    // ── Calls ─────────────────────────────────────
    'calls.title':        'Calls',
    'calls.tab.logs':     '📞 Calls',
    'calls.tab.twilio':   '🎙 Twilio Recordings',
    'calls.stat.total':   'Total',
    'calls.stat.completed':'Completed',
    'calls.stat.noAnswer': 'No answer',
    'calls.stat.recordings':'Recordings',
    'calls.stat.duration': 'Total time',
    'calls.filter.number': 'Search number or agent...',
    'calls.filter.allStatus': 'All statuses',
    'calls.filter.allRec':    'All recordings',
    'calls.filter.withRec':   'With recording',
    'calls.filter.noRec':     'No recording',
    'calls.col.number':   'Number',
    'calls.col.agent':    'Agent',
    'calls.col.status':   'Status',
    'calls.col.duration': 'Duration',
    'calls.col.date':     'Date',
    'calls.col.lead':     'Lead',
    'calls.col.recording':'Recording',
    'calls.empty':        'No calls logged',
    'calls.status.completed':    'Completed',
    'calls.status.no-answer':    'No answer',
    'calls.status.busy':         'Busy',
    'calls.status.failed':       'Failed',
    'calls.status.initiated':    'Initiated',
    'calls.status.ringing':      'Ringing',
    'calls.status.in-progress':  'In progress',
    'calls.status.canceled':     'Canceled',
    'calls.outbound':            'Outbound',
    'calls.inbound':             'Inbound',
    'calls.rec.loading':         'Loading recording...',
    'calls.rec.error':           'Error loading recording',
    'calls.rec.confirmDelete':   'Delete recording?',
    'calls.rec.deleting':        'Deleting...',
    'calls.rec.noAudio':         'Your browser does not support HTML5 audio.',
    'calls.rec.play':            '▶ Play',
    'calls.rec.pause':           '⏸ Pause',
    'calls.rec.transcribe':      '✍ Transcribe',
    'calls.rec.processing':      'Processing...',
    'calls.rec.download':        '⬇ Download',
    'calls.rec.delete':          'Delete recording',
    'calls.rec.conversation':    'Conversation ({n} turns)',
    'calls.rec.transcript':      'Transcript',
    'calls.rec.noTranscript':    'No transcribable content in this recording.',
    'calls.rec.agent':           'Agent',
    'calls.rec.client':          'Client',
    'calls.rec.stereo':          'Stereo',
    'calls.rec.mono':            'Mono',
    'calls.rec.voicemail':       '📩 Voicemail',
    'calls.rec.call':            '📞 Call',
    'calls.rec.play_btn':        'Play recording',
    'calls.rec.close_btn':       'Close player',

    // ── Leads ──────────────────────────────────────
    'leads.tab.chat':      'Chat',
    'leads.tab.notes':     'Notes',
    'leads.tab.tasks':     'Tasks',
    'leads.tab.calls':     'Calls',
    'leads.tab.activity':  'Activity',
    'leads.tab.tags':      'Tags',
    'leads.tab.extra':     'Extra',
    'leads.tab.trip':      'Trip',
    'leads.tab.contacts':  'Contacts',
    'leads.tab.intNotes':  'Int. notes',
    'leads.tab.ai':        'AI',
    'leads.stage':         'Stage...',
    'leads.select':        'Select',
    'leads.automate':      'Automate',
    'leads.newLead':       'New lead',
    'leads.dormant':       'Dormant',
    'leads.dormantTitle':  'Leads with no activity for more than 7 days',
    'leads.botOn':         'ON',
    'leads.botOff':        'OFF',
    'leads.summarize':     'AI Summary',
    'leads.summarizing':   'Summarizing...',
    'leads.merge':         'Merge leads',
    'leads.mergeTitle':    'Merge with another lead',
    'leads.mergeDesc':     'Lead {title} will be kept. Messages, notes, tasks, and contacts from the other lead will be transferred here and that lead will be deleted.',
    'leads.mergeSearch':   'Search lead by name or contact...',
    'leads.outbound':      'Outbound',
    'leads.inbound':       'Inbound',
    'leads.noSubject':     'No subject',
    'leads.status.completed':  'Completed',
    'leads.status.no-answer':  'No answer',
    'leads.status.busy':       'Busy',
    'leads.status.failed':     'Failed',
    'leads.status.initiated':  'Initiated',
    'leads.status.ringing':    'Ringing',
    'leads.status.in-progress':'In progress',
    'leads.status.canceled':   'Canceled',
    'leads.rec.loading':       'Loading recordings...',
    'leads.rec.noTwilio':      'No Twilio recordings',
    'leads.rec.errorDelete':   'Error deleting: ',

    // ── Contacts ──────────────────────────────────
    'contacts.editTitle':    'Edit contact',
    'contacts.newTitle':     'New contact',
    'contacts.name':         'Name *',
    'contacts.phone':        'Phone',
    'contacts.email':        'Email',
    'contacts.company':      'Company',
    'contacts.notes':        'Notes',
    'contacts.namePH':       'John Doe',
    'contacts.phonePH':      '+1234567890',
    'contacts.emailPH':      'email@example.com',
    'contacts.companyPH':    'Company name',
    'contacts.notesPH':      'Internal notes...',
    'contacts.dupWarning':   'Already exists: {name}. Create anyway?',
    'contacts.viewExisting': 'View existing contact',
    'contacts.createAnyway': 'Create anyway',
    'contacts.import':       'Import contacts from CSV',
    'contacts.importStep':   'Step {n} of 2',
    'contacts.importHint':   'The first row must be the header. Then you can map the columns.',
    'contacts.importClick':  'Click to select CSV',
    'contacts.importMap':    'Map each CSV column to the corresponding field.',
    'contacts.importPreview':'Preview →',
    'contacts.importBack':   'Back',
    'contacts.importRequire':'You must map at least the "Name" column.',
    'contacts.importPreviewLabel': 'Preview ({n} of {total} rows):',
    'contacts.importBtn':    'Import {n} contacts',
    'contacts.importDone':   'Import complete',
    'contacts.importResult': '{n} contacts created · {s} skipped (duplicates)',
    'contacts.dupDetect':    'Detect duplicates',
    'contacts.dupDesc':      'Contacts with the same phone or identical name',
    'contacts.dupSearching': 'Searching for duplicates...',
    'contacts.dupNone':      'No duplicate contacts found',
    'contacts.dupPhone':     '📞 Same phone',
    'contacts.dupName':      '👤 Same name',
    'contacts.dupKeep':      'Keep "{name}"',
    'contacts.dupMerging':   'Merging...',
    'contacts.dupSkip':      'Skip',
    'contacts.col.name':     'Name',
    'contacts.col.phone':    'Phone',
    'contacts.col.email':    'Email',
    'contacts.col.company':  'Company',
    'contacts.exportCsv':    'Export CSV',
    'contacts.export':       'Export',
    'contacts.import2':      'Import',
    'contacts.newShort':     'New',

    // ── Inbox ──────────────────────────────────────
    'inbox.title':           'INBOX',
    'inbox.empty':           'No conversations',
    'inbox.search':          'Search...',
    'inbox.send':            'Send',
    'inbox.typePlaceholder': 'Type a message...',
    'inbox.noMessages':      'No messages',
    'inbox.inbound':         'Inbound',
    'inbox.outbound':        'Outbound',
    'inbox.channel.whatsapp':'WhatsApp',
    'inbox.channel.sms':     'SMS',
    'inbox.channel.email':   'Email',

    // ── Settings ───────────────────────────────────
    'settings.templates':      'Quick reply templates',
    'settings.templatesDesc':  'Predefined responses to use in the inbox.',
    'settings.templatesVars':  'Variables: {{nombre}}, {{telefono}}, {{fecha}}, {{fecha_checkin}}, {{monto}}, {{agente}}',
    'settings.general':        'General',
    'settings.editTemplate':   'Edit template',
    'settings.newTemplate':    'New template',
    'settings.titlePH':        'Title (e.g. Welcome)',
    'settings.categoryPH':     'Category (e.g. Sales)',
    'settings.textPH':         'Text... you can use the variables above',
    'settings.noTemplates':    'No templates yet',
    'settings.customFields':   'Custom fields',
    'settings.customFieldsDesc':'Add extra fields to leads and contacts',
    'settings.cfLeads':        'Leads',
    'settings.cfContacts':     'Contacts',
    'settings.cfEmpty':        'No custom fields yet',
    'settings.cfNew':          'New field',
    'settings.cfLabelPH':      'Field label (e.g. Budget, Role)',
    'settings.cfText':         'Text',
    'settings.cfNumber':       'Number',
    'settings.cfDate':         'Date',
    'settings.cfSelect':       'Select',
    'settings.cfOptionsPH':    'Options separated by comma (e.g. Option 1, Option 2)',
    'settings.cfAdd':          'Add field',
  },
};

export default strings;
